name: ludotitian
description: "A multiplayer Ludo game application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  shared_preferences: ^2.2.2
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  audioplayers: ^6.5.1

  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.1
  equatable: ^2.0.5

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Utilities
  uuid: ^4.2.2
  intl: ^0.18.1
  url_launcher: ^6.3.2
  image_picker: ^1.0.7
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "images/ludo_logo.jpg"
  android_adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
